name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-restore
      
    - name: Publish
      run: dotnet publish -c Release -o out
          
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.5.1
      with:
        build_dir: ./out/wwwroot
      env:
        GITHUB_PAT: ${{ secrets.PAT }}


